Header header

RadarPoint32[] points

string timestamp
string radar_cfg

float32[] range_profile
bool range_profile_valid

float32[] noise_profile
bool noise_profile_valid

float32[] azimuth_static
bool azimuth_static_valid

float32[] range_doppler
bool range_doppler_valid


int16 num_tx_antenna
int16 num_tx_azimuth_antenna
int16 num_tx_elev_antenna
int16 num_rx_antenna

int16 num_range_bin
int16 num_doppler_bin
int16 num_angular_bin


float32 bandwidth
float32 range_resolution
float32 range_bin

float32 doppler_resolution
float32 angular_resolution
float32 range_unambiguous
float32 range_maximum
float32 doppler_maximum